### ISSUE TITLE
Termination issues with unsupported patterns

### ISSUE THREAD

**Issue by just95** [FreeProving/haskell-src-transformations#13]
### Description

If there are unsupported patterns, the pattern matching compiler sometimes does not terminate.

### Steps to Reproduce

> **Warning:** when you try to reproduce the bug, keep an eye on your system memory and be prepared to cancel compilation (e.g., using <kbd>CTRL</kbd> + <kbd>C</kbd>). The pattern matching compiler will consume high amounts of memory which can impair system responsiveness and stability.

1. Consider the following module.

    ```haskell
    module Test where

    duplicateHead :: [a] -> [a]
    duplicateHead []           = []
    duplicateHead xs@(x : xs') = x : xs
    ```

2. Run the pattern matching compiler on the module above wtih one of the following commands.

    ```bash
    haskell-src-transformations -I Test.hs
    cabal new-run exe:haskell-src-transformations -- -I Test.hs
    ```

#### Expected Behavior

Since as-patterns are not supported, an error should be reported.

#### Actual Behavior

The pattern matching compiler does not terminate and consumes as much memory as it can.

The most likely cause for this behavior is in the [`match` Algorithm](https://github.com/FreeProving/haskell-src-transformations/blob/master/src/lib/Algo.hs#L59). Unsupported patterns are neither considered constructor nor variable patterns. Thus, neither *Rule 1* nor *Rule 2* applies in the presence of unsupported patterns. The unconditional recursion in *Rule 4* prevents termination.

### Versions

 - Git commit: 504cf38dbb871def1b625eccab4ec6070e8a9c2f 
 - `ghc --version`: 8.6.5 
 - `cabal --version`: 2.4.1.0 
 - OS: Ubuntu 19.10

**Comment by stu204767** [comment]
Should we close this issue? The bug specified here doesn't occur anymore since we switched to our own syntax. Or are there still bugs associated with this one?

**Comment by just95** [comment]
I think that we should still try to fix the root cause of the issue (i.e., the incomplete guards in `match`) to prevent (or at least avoid) that the bug resurfaces in the future.
